### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by xzllxls** [LantaoYu/Residual-Networks#1]
Hello, I execute the program, but error occurs.

When the program run at line 23 in function __init__ of data_loader.py, error occurs as following:
Traceback (most recent call last):
  File "D:\workspacePython\ResidualLearning-github\main.py", line 46, in <module>
    dataloader = CIFAR_loader(params)
  File "D:\workspacePython\ResidualLearning-github\data_loader.py", line 23, in __init__
    datadict = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 6: ordinal not in range(128)

Even through I transform the codec to UTF-8
```
datadict = pickle.load(f, encoding="UTF-8")
```
 error also appears.

Traceback (most recent call last):
  File "D:\workspacePython\ResidualLearning-github\main.py", line 46, in <module>
    dataloader = CIFAR_loader(params)
  File "D:\workspacePython\ResidualLearning-github\data_loader.py", line 24, in __init__
    datadict = pickle.load(f, encoding="UTF-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 6: invalid start byte

I do not know why.

Can anyone help me ?

Thanks!

**Comment by prajjwal1** [comment]
I searched online, try this out:
cPickle.load(file, encoding='latin1')

**Comment by rchavezj** [comment]
@prajjwal1 Is cPickle a different imported library?

**Comment by alansoft** [comment]
> @prajjwal1 Is cPickle a different imported library?

cPickle is the same library of pickle in python 2.x
